In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn import datasets
import pydotplus
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = iris.data      #特徵
y = iris.target    #目標

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
clf = tree.DecisionTreeClassifier(criterion="entropy").fit(X, y)

In [8]:
clf.score(X, y)     #分類效果，1表示模型100%建構完成

1.0

# 決策樹模型輸出

In [ ]:
dot_data = tree.export_graphviz(clf, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('iris.pdf')                       #pdf輸出

# 拆分訓練集與測試集

為了避免overfitting，所以拆分

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3)

In [11]:
clf = tree.DecisionTreeClassifier(criterion='entropy').fit(X_train, y_train)

In [12]:
clf.score(X_train, y_train)   #成效

1.0

In [13]:
clf.predict(X_test)

array([0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1,
       2, 1, 0, 2, 2, 0, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 0, 0, 1,
       1])

In [14]:
clf.score(X_test, y_test)     #成效

0.9777777777777777

# 過度配適初步調整

overfitting調整

entropy 區分

In [15]:
clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3).fit(X_train, y_train)

假設，樹只長3層

In [16]:
clf.predict(X_test)

array([0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1,
       2, 1, 0, 2, 2, 0, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 0, 0, 1,
       1])

In [17]:
clf.score(X_train,y_train)

0.9523809523809523

In [18]:
clf.score(X_test,y_test)

0.9777777777777777

gini 區分

In [19]:
clf = tree.DecisionTreeClassifier(criterion='gini', max_depth=3).fit(X_train, y_train)

In [20]:
clf.predict(X_test)

array([0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1,
       2, 1, 0, 2, 2, 0, 2, 2, 2, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 0, 0, 1,
       1])

In [21]:
clf.score(X_test,y_test)

0.9777777777777777

In [ ]:
dot_data=tree.export_graphviz(clf,out_file=None)
graph=pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('iris_gini_max3.pdf')